#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Set some variables expected by packages. Harmless if packages aren't
# present
# define a download cache for pip. A bit os X centric at present
export PIP_DOWNLOAD_CACHE=$HOME/Library/Caches/pip-downloads
# Use distribute by default for virtualenvs

# define the GOPATH as required by golang
export GOPATH=${HOME}/go

#
# Paths
#

typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

path=(
  /usr/local/{bin,sbin}
  $path
)

# Set the brew prefix if brew exists and add additional dirs to path
if (( $+commands[brew] )); then
  brew_prefix=$(brew --prefix)
    if [[ -d ${brew_prefix}/share/npm ]] ; then
    path=(
      ${brew_prefix}/share/npm/bin
      $path
    )
  fi
fi

# Set the list of directories that Zsh searches for programs.
path=(
  ${HOME}/bin
  ${GOPATH}/bin
  $path
)


#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

[[ "${OSTYPE}" == darwin* ]] && export JAVA_HOME=$(/usr/libexec/java_home)
[[ -f "${HOME}/.aws_util_creds" ]] && export AWS_CREDENTIAL_FILE="${HOME}/.aws_util_creds"

