#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
[[ -s $(brew --prefix)/etc/autojump.sh ]] && . $(brew --prefix)/etc/autojump.sh

# include API keys, access tokens etc. that we don't want to commit to public repos
[[ -f ${HOME}/.cred_env_vars ]] && . ${HOME}/.cred_env_vars

# load in aliases
[[ -f ${HOME}/.aliases ]] && . ${HOME}/.aliases

# set git user info if globally configured
if [[ -f ${HOME}/.gitconfig ]] ; then
    GIT_AUTHOR_NAME=$(git config user.name)
    GIT_AUTHOR_EMAIL=$(git config user.email)
    GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
    GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
fi

echo "export PATH=${PATH}" >! ~/.bash_profile

